### ISSUE TITLE
Change style

### ISSUE THREAD

**Issue by rani-agrawal12** [alx/react-bounding-box#27]
Hello, I am trying to change the border of the bounding box and the font size of the label. Can you please suggest the solution for this.

**Comment by alx** [comment]
Hi @rani-agrawal12 

You can change the bounding box colors using `options.colors` props - https://github.com/alx/react-bounding-box/blob/master/src/react-bounding-box.js#L546

For font size, the easier way would be to replace the default `drawLabel` function prop and modify the `ctx.font` value - https://github.com/alx/react-bounding-box/blob/master/src/react-bounding-box.js#L541

Feel free to ask if it's not clear. Have a nice day,

Alex

**Comment by rani-agrawal12** [comment]
I want to change the thickness of the bounding box and style like I want rectangle or 4 corner as a bounding box so how could I do that. Can you please suggest solution for that.

**Comment by alx** [comment]
Box drawing is made in `Boundingbox.defaultProps.drawBox` method - https://github.com/alx/react-bounding-box/blob/master/src/react-bounding-box.js#L439 - and can be replaced by implementing your own drawing method on this prop.

It's a simple canvas path, it should be easy to make and decorate your own path.

**Comment by rani-agrawal12** [comment]
Okay, Thank You
