### ISSUE TITLE
Bump react version in peer dependency

### ISSUE THREAD

**Issue by johanbook** [alx/react-bounding-box#29]
React and React-dom peer versions should be bumped to 16 (maybe even allow 17).  It also looks malformatted as it requires
```
^0.14.7 || ^15.0.0"
```

**Comment by johanbook** [comment]
@alx

**Comment by alx** [comment]
Hi @johanbook 

Thanks for the notification, I've updated the `package.json` file.

Feel free to comment about this change and propose a pull-request to modify it.

Alex
