### ISSUE TITLE
Selecting Single Element

### ISSUE THREAD

**Issue by sumitbhavra** [alx/react-bounding-box#7]
Hi, Hope you are fine. It not an issue I just want to clarify something. I get my coordinating in drop down and when user select that coordinates. I only want to display that text highlighted. Please let me know how I can do it with react-bounding-box
Thanks
Sumit

**Comment by alx** [comment]
Hi Sumit,

I'm not sure how to help you, do you have some code/demo somewhere so I could have a quick look?

I'm closing this issue but you can continue to comment on it, I'll try to answer you the best I can.

Thanks,

Alex
